config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'welcome#index'

get 'sessions/new'

get '/', to: 'welcome#index', as: 'home'

get('/contact', { to: 'welcome#contact'})

post('/contact_submit', { to: 'welcome#submit' })

resources :ideas

resources :ideas do
  resources :reviews, only: [:show, :new, :create, :edit, :destroy]
end

  resources :sessions, only: [:new, :create, :edit] do
    # when you define a route with 'on: :collection' option, it skips requiring an :id
    delete :destroy, on: :collection
  end

  resources :users
  resources :welcome
  resources :reviews


  # resources :ideas do
  #   resources :answers, only: [:create, :destroy]
  #   #adds the following nested routes:
  #   #/questions/:question_id/answers VERB: post
  #   #/questions/:question_id/answers/:id VERB: delete
  # end


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user, optional: true


  validates(:title, { presence: {message: 'must be provided'},
                      uniqueness: true })
  validates(:body, {length: {minimum: 5, maximum: 1000}})

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password


  has_many :ideas, dependent: :nullify
  has_many :reviews, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    # the below is to prevent the app from crashing if we have a user_id in the session and no user with that id in the databse. This occurs when a logged in user is deleted
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end
  # the below makes the method available to all my views
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, notice: 'Please Sign In!'
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :review_params, only: [:show, :edit, :update, :destroy]
  # before_action  @reviews = Review.find(params[:id]
  before_action :authenticate_user!, except: [:index, :show]

  # before_action :find_question, only: [:show, :edit, :update, :destroy]

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      flash[:notice] = 'Idea created'
      redirect_to idea_path(@idea)
    else
      flash.now[:alert] = 'Please fix errors below'
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
    @review = Review.new
  end

  def index
    @ideas = Idea.all
  end

  def edit
    unless can? :edit, @idea
      flash[:notice] = 'You cannot edit something that is not yours'
      redirect_to @idea
    end
  end

  def update
    if !(can? :update, @idea)
      head :unauthorized
    elsif @idea.update(idea_params)
      # if you have a `redirect_to` and you'd like to specify a flash message
      # then you can just pass in the `flash` or `alert` as options to the
      # `redirect_to` instead of having a separate line. Please note that this
      # does not work with `render`
      redirect_to idea_path(@idea), notice: 'Idea updated'
    else
      render :edit
    end
  end

  def destroy
    if can? :destroy, @idea
      @idea.destroy
      redirect_to ideas_path, notice: 'Idea deleted'
    else
      head :unauthorized
    end
  end

  private

  def idea_params
    params.require(:idea).permit([:title, :body])
  end


  def find_idea
    @idea = Idea.find params[:id]
  end

  def review_params
    @reviews = Review.find params[:id]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]



  def create
    @review = Review.new(review_params)
    @user = User.new(user_params)
    @review.idea = @idea
    @review.user = current_user
    if cannot? :create, @review
      flash[:alert] = "Access Denied. You cannot review your own product"

    elsif @review.save
      flash[:notice] = "Review Created"
      redirect_to idea_path(@idea), notice: 'Thank you for submitting a review!'
    else
      flash[:alert] = "Problem creating review"
      render 'ideas/show'
    end
  end



  def destroy
    @review = Review.find params[:id]
    @idea = @review.idea

    if can? :destroy, @review
    @review.destroy
    redirect_to idea_path(@idea), alert: 'Review removed'
  else
    flash[:alert] = "Access Denied. You cannot delete that review"
    redirect_to @review.idea
  end
    # render json: params
  end

  def hide
    @review = Review.find params[:id]
    @idea = @review.idea
    # @review.hidden = true
    @review.save

    redirect_to idea_path(@idea), alert: 'Review hidden'


  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    user = User.find_by(email: params[:email])

    user.password  = params[:password]
    user.password_confirmation = params[:password_confirmation]
    user.save

    session[:user_id] = user.id
    if user&.authenticate(params[:password])
      redirect_to home_path, notice: 'Thanks for signing in!'
    else
      # flash.now makes the flasth message available to the current request as opposed to next request with just 'flash'
      flash.now[:alert] = "Wrong credentials, thief!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: 'Signed Out!'
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path
    else
      render :new
    end
  end

  def edit
    
  end


  private


  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @ideas = Idea.all.order(created_at: :desc)
  end

  def show

  end

  def submit

  end

  private

  def find_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:ideas).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/index.html.erb
<% @ideas.each do |idea|  %>
<h4><%= link_to idea.title, idea_path(idea)  %></h4>
<br>
<p><%= idea.body  %></p>
<% if (can? :edit, idea) %>
<%= link_to 'Edit', welcome_index_path %>
<% end %>

<% if (can? :destroy, idea) %>
<%= link_to 'Delete', welcome_index_path  %>
<% end %>

<div class="row">
  <div class="col-md-5">
    <div class="row">
      <div class="col-md-4">
        <div class="">
          <%= link_to 'Edit', welcome_index_path %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="inner-idea-box">
          Join
        </div>
      </div>
      <div class="col-md-4">
        <div class="inner-idea-box">
          Liked
        </div>
      </div>
    </div>

  </div>
  <div class="col-md-7">
    <div class="row">
      <div class="col-md-7">

      </div>
      <div class="col-md-5">
        Members 5 | Likes 6
      </div>
    </div>

  </div>

</div>
<hr>
<% end %>

app/views/ideas/new.html.erb
<h1>new idea</h1>

<%= form_for @idea do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/ideas/show.html.erb
<!-- <h1>This is the idea show page</h1> -->
<br>
<h2><%= @idea.title  %></h2>
<br>
<p><%= @idea.body  %></p>
<p>Submitted by <%= @idea.user.try(:username) %></p>

<% if (can? :edit, @idea) %>
<%= link_to 'Edit', edit_idea_path(@idea) %>
<% end %>

<% if (can? :destroy, @idea) %>
<%= link_to 'Delete', idea_path(@idea),
                                    method: :delete,
                                    data: { confirm: 'really?'}  %>
<% end %>

<br>
<% if current_user != @idea.user %>
<% if @review.errors.any? %>
<h2><%=@review.errors.full_messages.join(', ')  %></h2>
<% end %>
<div>
  <%= form_for ([@idea, @review]) do |f|  %>
  <h3>Add a Review</h3>
    <% f.label :body %>
    <%= f.text_area :body  %>
    <br>
    <%= f.select :rating, [5,4,3,2,1]  %>
    <br>
    <%= f.submit :submit  %>
  <% end %>

</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- <div class="container col-md-8 offset-md-2">
      <div class="row"> -->
        <div class="container">

              <%# link_to: is a built-in Rails helper method to generate a <a> link, the first argument is the anchor text and second argument  %>
              <div class="row">
                <div class="logo col-md-4">

                  <%= image_tag 'factory.png', size: "150"  %>
                  <h3><%= link_to('Idea Factory', home_path) %></h3>
                </div>
                <div class="right-head col-md-4 offset-md-4">
                  <div class="">
                    <% if user_signed_in?  %>
                  <h4>Hello <%= current_user.username  %>
                    <%= link_to 'Sign Out', sessions_path, method: :delete  %>
                    <% else %>

                  <%= link_to 'Sign In', new_session_path  %>
                    <%= link_to 'Sign Up', new_user_path  %></h4>
                    <% end %>
                  </div>
                  <div class="idea-box">
                    <%= link_to 'Submit Idea', new_idea_path  %>
                  </div>
                  </div>

              </div>

              <br>
              <hr>



              <% if flash[:notice] %>
                <div class='alert alert-success'><%= flash[:notice] %></div>
              <% elsif flash[:alert] %>
                <div class='alert alert-danger'><%= flash[:alert] %></div>
              <% end %>


              <%= yield %>
        </div>
      <!-- </div>
    </div> -->


  </body>
</html>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>


<%= @user.errors.full_messages.join(', ')  %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="jumbotron col-md-6 offset-md-3 front-jumbo">
    <h2>Welcome To The Idea Factory!</h2>
    <br>
    <p>The idea factory is your best choice for finding projects to work on, and for submitting your best ideas to be voted on by a community of like minded professionals. You can also find people to joint venture with, and maybe build something a little out of your comfort zone!</p>
    <h3><%= link_to('The Factory Line', ideas_path) %></h3>
  </div>
</div>